"""
config包的初始化文件
"""

from .config import API_KEY, ENDPOINTS, DEFAULT_UNITS, DEFAULT_LANG, DEFAULT_CITY, WEATHER_LAYERS

__all__ = ['API_KEY', 'ENDPOINTS', 'DEFAULT_UNITS', 'DEFAULT_LANG', 'DEFAULT_CITY', 'WEATHER_LAYERS'] 